//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Playground.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Playground.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ButtonTextAuth {
            get {
                return ResourceManager.GetString("ButtonTextAuth", resourceCulture);
            }
        }
        
        internal static string ButtonTextRemoteConfig {
            get {
                return ResourceManager.GetString("ButtonTextRemoteConfig", resourceCulture);
            }
        }
        
        internal static string ButtonTextStorage {
            get {
                return ResourceManager.GetString("ButtonTextStorage", resourceCulture);
            }
        }
        
        internal static string ButtonTextFetchRemoteConfig {
            get {
                return ResourceManager.GetString("ButtonTextFetchRemoteConfig", resourceCulture);
            }
        }
        
        internal static string ButtonTextUploadText {
            get {
                return ResourceManager.GetString("ButtonTextUploadText", resourceCulture);
            }
        }
        
        internal static string ButtonTextSignInWithEmail {
            get {
                return ResourceManager.GetString("ButtonTextSignInWithEmail", resourceCulture);
            }
        }
        
        internal static string ButtonTextSignInWithGoogle {
            get {
                return ResourceManager.GetString("ButtonTextSignInWithGoogle", resourceCulture);
            }
        }
        
        internal static string ButtonTextSignOut {
            get {
                return ResourceManager.GetString("ButtonTextSignOut", resourceCulture);
            }
        }
        
        internal static string LabelUserIsSignedIn {
            get {
                return ResourceManager.GetString("LabelUserIsSignedIn", resourceCulture);
            }
        }
        
        internal static string LabelUserIsSignedOut {
            get {
                return ResourceManager.GetString("LabelUserIsSignedOut", resourceCulture);
            }
        }
        
        internal static string EntryPlaceholderStorage {
            get {
                return ResourceManager.GetString("EntryPlaceholderStorage", resourceCulture);
            }
        }
        
        internal static string DialogTitleUnexpectedError {
            get {
                return ResourceManager.GetString("DialogTitleUnexpectedError", resourceCulture);
            }
        }
        
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
    }
}
