//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Playground.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Playground.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth.
        /// </summary>
        internal static string ButtonAuth {
            get {
                return ResourceManager.GetString("ButtonAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check validity.
        /// </summary>
        internal static string ButtonCheckFcmValidity {
            get {
                return ResourceManager.GetString("ButtonCheckFcmValidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Messaging.
        /// </summary>
        internal static string ButtonCloudMessaging {
            get {
                return ResourceManager.GetString("ButtonCloudMessaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch and activate.
        /// </summary>
        internal static string ButtonFetchRemoteConfig {
            get {
                return ResourceManager.GetString("ButtonFetchRemoteConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link with email.
        /// </summary>
        internal static string ButtonLinkWithEmail {
            get {
                return ResourceManager.GetString("ButtonLinkWithEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link with facebook.
        /// </summary>
        internal static string ButtonLinkWithFacebook {
            get {
                return ResourceManager.GetString("ButtonLinkWithFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link with google.
        /// </summary>
        internal static string ButtonLinkWithGoogle {
            get {
                return ResourceManager.GetString("ButtonLinkWithGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link with phone number.
        /// </summary>
        internal static string ButtonLinkWithPhoneNumber {
            get {
                return ResourceManager.GetString("ButtonLinkWithPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register FCM token.
        /// </summary>
        internal static string ButtonRegisterFcmToken {
            get {
                return ResourceManager.GetString("ButtonRegisterFcmToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote config.
        /// </summary>
        internal static string ButtonRemoteConfig {
            get {
                return ResourceManager.GetString("ButtonRemoteConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password by email.
        /// </summary>
        internal static string ButtonSendEmailToResetPassword {
            get {
                return ResourceManager.GetString("ButtonSendEmailToResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send verification code.
        /// </summary>
        internal static string ButtonSendVerificationCode {
            get {
                return ResourceManager.GetString("ButtonSendVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string ButtonSignIn {
            get {
                return ResourceManager.GetString("ButtonSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in anonymously.
        /// </summary>
        internal static string ButtonSignInAnonymously {
            get {
                return ResourceManager.GetString("ButtonSignInAnonymously", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with apple.
        /// </summary>
        internal static string ButtonSignInWithApple {
            get {
                return ResourceManager.GetString("ButtonSignInWithApple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with email.
        /// </summary>
        internal static string ButtonSignInWithEmail {
            get {
                return ResourceManager.GetString("ButtonSignInWithEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with email link.
        /// </summary>
        internal static string ButtonSignInWithEmailLink {
            get {
                return ResourceManager.GetString("ButtonSignInWithEmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with facebook.
        /// </summary>
        internal static string ButtonSignInWithFacebook {
            get {
                return ResourceManager.GetString("ButtonSignInWithFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with google.
        /// </summary>
        internal static string ButtonSignInWithGoogle {
            get {
                return ResourceManager.GetString("ButtonSignInWithGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with phone number.
        /// </summary>
        internal static string ButtonSignInWithPhoneNumber {
            get {
                return ResourceManager.GetString("ButtonSignInWithPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        internal static string ButtonSignOut {
            get {
                return ResourceManager.GetString("ButtonSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        internal static string ButtonStorage {
            get {
                return ResourceManager.GetString("ButtonStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to topic.
        /// </summary>
        internal static string ButtonSubscribeToTopic {
            get {
                return ResourceManager.GetString("ButtonSubscribeToTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger notification.
        /// </summary>
        internal static string ButtonTriggerNotification {
            get {
                return ResourceManager.GetString("ButtonTriggerNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger notification via token.
        /// </summary>
        internal static string ButtonTriggerNotificationViaToken {
            get {
                return ResourceManager.GetString("ButtonTriggerNotificationViaToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger notification via topic.
        /// </summary>
        internal static string ButtonTriggerNotificationViaTopic {
            get {
                return ResourceManager.GetString("ButtonTriggerNotificationViaTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlink provider.
        /// </summary>
        internal static string ButtonUnlinkProvider {
            get {
                return ResourceManager.GetString("ButtonUnlinkProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregister FCM token.
        /// </summary>
        internal static string ButtonUnregisterFcmToken {
            get {
                return ResourceManager.GetString("ButtonUnregisterFcmToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe from topic.
        /// </summary>
        internal static string ButtonUnsubscribeFromTopic {
            get {
                return ResourceManager.GetString("ButtonUnsubscribeFromTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload text as file.
        /// </summary>
        internal static string ButtonUploadText {
            get {
                return ResourceManager.GetString("ButtonUploadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter some message you want to receive.
        /// </summary>
        internal static string DialogMessageEnterCloudMessageBody {
            get {
                return ResourceManager.GetString("DialogMessageEnterCloudMessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address.
        /// </summary>
        internal static string DialogMessageEnterEmail {
            get {
                return ResourceManager.GetString("DialogMessageEnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        internal static string DialogMessageEnterPassword {
            get {
                return ResourceManager.GetString("DialogMessageEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone number so Firebase can send a verification code.
        /// </summary>
        internal static string DialogMessageEnterPhoneNumber {
            get {
                return ResourceManager.GetString("DialogMessageEnterPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the topic.
        /// </summary>
        internal static string DialogMessageEnterTopic {
            get {
                return ResourceManager.GetString("DialogMessageEnterTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the verification code.
        /// </summary>
        internal static string DialogMessageEnterVerificationCode {
            get {
                return ResourceManager.GetString("DialogMessageEnterVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The validity check was successful.
        /// </summary>
        internal static string DialogMessageFcmValid {
            get {
                return ResourceManager.GetString("DialogMessageFcmValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your inbox, we&apos;ve sent a login link to your email address. Tap on the link to get signed in automatically..
        /// </summary>
        internal static string DialogMessageSignInLinkSent {
            get {
                return ResourceManager.GetString("DialogMessageSignInLinkSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the provider you want to unlink.
        /// </summary>
        internal static string DialogMessageUnlinkProvider {
            get {
                return ResourceManager.GetString("DialogMessageUnlinkProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud messaging.
        /// </summary>
        internal static string DialogTitleCloudMessaging {
            get {
                return ResourceManager.GetString("DialogTitleCloudMessaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login link sent.
        /// </summary>
        internal static string DialogTitleSignInLinkSent {
            get {
                return ResourceManager.GetString("DialogTitleSignInLinkSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error.
        /// </summary>
        internal static string DialogTitleUnexpectedError {
            get {
                return ResourceManager.GetString("DialogTitleUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlink provider.
        /// </summary>
        internal static string DialogTitleUnlinkProvider {
            get {
                return ResourceManager.GetString("DialogTitleUnlinkProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text for upload.
        /// </summary>
        internal static string EntryPlaceholderStorage {
            get {
                return ResourceManager.GetString("EntryPlaceholderStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are signed in:
        ///        Email: %1$s
        ///        Method: %2$s.
        /// </summary>
        internal static string LabelUserIsSignedIn {
            get {
                return ResourceManager.GetString("LabelUserIsSignedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are signed in without using an email address.
        /// </summary>
        internal static string LabelUserIsSignedInWithoutEmail {
            get {
                return ResourceManager.GetString("LabelUserIsSignedInWithoutEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are signed out.
        /// </summary>
        internal static string LabelUserIsSignedOut {
            get {
                return ResourceManager.GetString("LabelUserIsSignedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
    }
}
