//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Playground.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Playground.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ButtonAuth {
            get {
                return ResourceManager.GetString("ButtonAuth", resourceCulture);
            }
        }
        
        internal static string ButtonRemoteConfig {
            get {
                return ResourceManager.GetString("ButtonRemoteConfig", resourceCulture);
            }
        }
        
        internal static string ButtonStorage {
            get {
                return ResourceManager.GetString("ButtonStorage", resourceCulture);
            }
        }
        
        internal static string ButtonFetchRemoteConfig {
            get {
                return ResourceManager.GetString("ButtonFetchRemoteConfig", resourceCulture);
            }
        }
        
        internal static string ButtonUploadText {
            get {
                return ResourceManager.GetString("ButtonUploadText", resourceCulture);
            }
        }
        
        internal static string ButtonSignInAnonymously {
            get {
                return ResourceManager.GetString("ButtonSignInAnonymously", resourceCulture);
            }
        }
        
        internal static string ButtonSignInWithEmail {
            get {
                return ResourceManager.GetString("ButtonSignInWithEmail", resourceCulture);
            }
        }
        
        internal static string ButtonSignInWithEmailLink {
            get {
                return ResourceManager.GetString("ButtonSignInWithEmailLink", resourceCulture);
            }
        }
        
        internal static string ButtonSignInWithGoogle {
            get {
                return ResourceManager.GetString("ButtonSignInWithGoogle", resourceCulture);
            }
        }
        
        internal static string ButtonSignInWithFacebook {
            get {
                return ResourceManager.GetString("ButtonSignInWithFacebook", resourceCulture);
            }
        }
        
        internal static string ButtonSignInWithPhoneNumber {
            get {
                return ResourceManager.GetString("ButtonSignInWithPhoneNumber", resourceCulture);
            }
        }
        
        internal static string ButtonSendVerificationCode {
            get {
                return ResourceManager.GetString("ButtonSendVerificationCode", resourceCulture);
            }
        }
        
        internal static string ButtonLinkWithEmail {
            get {
                return ResourceManager.GetString("ButtonLinkWithEmail", resourceCulture);
            }
        }
        
        internal static string ButtonLinkWithGoogle {
            get {
                return ResourceManager.GetString("ButtonLinkWithGoogle", resourceCulture);
            }
        }
        
        internal static string ButtonLinkWithFacebook {
            get {
                return ResourceManager.GetString("ButtonLinkWithFacebook", resourceCulture);
            }
        }
        
        internal static string ButtonLinkWithPhoneNumber {
            get {
                return ResourceManager.GetString("ButtonLinkWithPhoneNumber", resourceCulture);
            }
        }
        
        internal static string ButtonUnlinkProvider {
            get {
                return ResourceManager.GetString("ButtonUnlinkProvider", resourceCulture);
            }
        }
        
        internal static string ButtonSignIn {
            get {
                return ResourceManager.GetString("ButtonSignIn", resourceCulture);
            }
        }
        
        internal static string ButtonSignOut {
            get {
                return ResourceManager.GetString("ButtonSignOut", resourceCulture);
            }
        }
        
        internal static string LabelUserIsSignedIn {
            get {
                return ResourceManager.GetString("LabelUserIsSignedIn", resourceCulture);
            }
        }
        
        internal static string LabelUserIsSignedInWithoutEmail {
            get {
                return ResourceManager.GetString("LabelUserIsSignedInWithoutEmail", resourceCulture);
            }
        }
        
        internal static string LabelUserIsSignedOut {
            get {
                return ResourceManager.GetString("LabelUserIsSignedOut", resourceCulture);
            }
        }
        
        internal static string EntryPlaceholderStorage {
            get {
                return ResourceManager.GetString("EntryPlaceholderStorage", resourceCulture);
            }
        }
        
        internal static string DialogTitleUnexpectedError {
            get {
                return ResourceManager.GetString("DialogTitleUnexpectedError", resourceCulture);
            }
        }
        
        internal static string DialogMessageEnterEmail {
            get {
                return ResourceManager.GetString("DialogMessageEnterEmail", resourceCulture);
            }
        }
        
        internal static string DialogMessageEnterPassword {
            get {
                return ResourceManager.GetString("DialogMessageEnterPassword", resourceCulture);
            }
        }
        
        internal static string DialogMessageEnterPhoneNumber {
            get {
                return ResourceManager.GetString("DialogMessageEnterPhoneNumber", resourceCulture);
            }
        }
        
        internal static string DialogMessageEnterVerificationCode {
            get {
                return ResourceManager.GetString("DialogMessageEnterVerificationCode", resourceCulture);
            }
        }
        
        internal static string DialogTitleSignInLinkSent {
            get {
                return ResourceManager.GetString("DialogTitleSignInLinkSent", resourceCulture);
            }
        }
        
        internal static string DialogMessageSignInLinkSent {
            get {
                return ResourceManager.GetString("DialogMessageSignInLinkSent", resourceCulture);
            }
        }
        
        internal static string DialogTitleUnlinkProvider {
            get {
                return ResourceManager.GetString("DialogTitleUnlinkProvider", resourceCulture);
            }
        }
        
        internal static string DialogMessageUnlinkProvider {
            get {
                return ResourceManager.GetString("DialogMessageUnlinkProvider", resourceCulture);
            }
        }
        
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
    }
}
